name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Environment Variables
        run: |
          echo "sql_server_host=${{ secrets.sql_server_host }}" >> $GITHUB_ENV
          echo "sql_http=${{ secrets.sql_http }}" >> $GITHUB_ENV
          echo "mydbtoken=${{ secrets.mydbtoken }}" >> $GITHUB_ENV
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        env: 
            mydbtoken=: ${{ secrets.MYDBTOKEN }}
            sql_server_host: ${{ secrets.SQL_SERVER_HOST }}
            sql_http: ${{ secrets.SQL_HTTP }}
        run: make test
      - name: format
        run: make format